name: Branch Publisher

on: 
  workflow_dispatch:
  push:
    # branches:
    #   - "release/**"
    #   - "hotfix/**"
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: write
  pull-requests: write

jobs:
  tester: 
    uses: ./.github/workflows/python_tester.yml

  create-pull-requests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        Branch: [development, main]
    needs: 
      - tester
    steps:
      - uses: actions/checkout@v4

      - name: Pull Requests
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: ${{ matrix.Branch }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_label: "automated pr"
          pr_title: "Merge into '${{ matrix.Branch }}'."
    