name: Python Testing

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - "main"
      - "development"
      - "release/**"
      - "hotfix/**"
  pull_request:
    branches:
      - "main"
      - "development"

permissions: 
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Unittests
        run: |
          python -m unittest discover 

      - name: Django Tests
        run: |
          if [ -f manage.py ]; then python manage.py test; fi

      - name: End to End Django Tests
        run: |
          if [ -f manage.py ]; then python manage.py test -p EndToEndTest*.py; fi

